### ISSUE TITLE
Thanks for making such a great library

### ISSUE THREAD

**Issue by chenshuiluke** [lsm/alfa#5]
I just wanted to let you know that this library has undeniably made development of a current project of mine much easier than it otherwise would have been. It's so easy to understand and setup that I'll probably be using it in most of my projects going forward :smile: :100: :+1:

**Comment by lsm** [comment]
@chenshuiluke Thanks for your kind words!  Let me know if you find any issues or if you have any suggestions.  Let's make it better together 😄
